version: '3'

services:

#PHP Service
  php:
    build: docker/php
    container_name: php_laravel
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks: 
      - net

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx_laravel
    restart: always
    depends_on:
      - php
      - phpmyadmin
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    networks: 
      - net
  
  #MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_laravel
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks: 
      - net
   
  #PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_laravel
    restart: always
    ports:
      - "4040:80"
    volumes:
      - /sessions
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql 
    links:
      - mysql
    networks: 
      - net

  #Redis
  redis:
    image: redis:latest
    container_name: redis_laravel
    ports:
      - 6379:6379
    networks: 
      - net

networks: 
  net: